spring:
  servlet:
    multipart:
      max-file-size: 10MB       #上传单个文件大小
      max-request-size: 10MB    #请求数据大小
  application:
    name: file                  #服务的名字
server:
  port: 18082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka     #Eureka注册地址
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true